[project]
name = "terminal-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.21.1",
]

[tool.mcp]
entrypoints = ["main.py"]
